#!/usr/bin/env bash

if [ -z "${VERSION}" ]; then
  echo "No version provided."
  exit 1
fi

PACKAGE=vim

set_variables

if _install; then
  require_hg
  cd $SRC_PATH

  # Keep a master repository.
  if [ ! -d "${PACKAGE}-repository" ]; then
    hg clone https://vim.googlecode.com/hg/ $PACKAGE-repository
  else
    pushd $PACKAGE-repository > /dev/null
      hg pull
    popd
  fi

  if [ ! -d ${STOW} ]; then
    hg clone --updaterev $VERSION $PACKAGE-repository $STOW
  fi

  cd $STOW
  ./configure \
    --prefix=$PREFIX \
    --enable-gui=no \
    --without-x \
    --disable-nls \
    --enable-multibyte \
    --with-tlib=ncurses \
    --enable-pythoninterp \
    --enable-rubyinterp \
    --enable-cscope \
    --with-ruby-command=/usr/bin/ruby \
    --with-features=huge
  make && make install
fi
