#!/usr/bin/env bash

PACKAGE=duplicity
VERSION='head'

set_variables

if _install; then
  require_bzr
  cd $SRC_PATH
  if [ ! -d $STOW ]; then
    bzr branch lp:duplicity $STOW
  fi
  cd $STOW
  python dist/setup.py install --prefix=$PREFIX
fi
