#!/usr/bin/env bash

PACKAGE=git

require_version
set_variables

if _install; then
  cd $SRC_PATH
  curl -O http://git-core.googlecode.com/files/$STOW.tar.gz
  tar xzf $STOW.tar.gz
  cd $STOW
  ./configure \
    --prefix=$PREFIX
  make && make install

  COMPLETION_PATH=$PREFIX/etc/bash_completion.d
  mkdir -p $COMPLETION_PATH
  cp $SRC_PATH/$STOW/contrib/completion/git-completion.bash $COMPLETION_PATH
fi
