#!/usr/bin/env bash

PACKAGE=mariadb

require_version
set_variables

if _install; then
  cd $SRC_PATH

  # HACK
  $STOW=$STOW-ga

  URL="http://ftp.osuosl.org/pub/mariadb/mariadb-5.3.5-ga/kvm-tarbake-jaunty-x86/$STOW.tar.gz"
  curl -O $URL
  tar xzf $STOW.tar.gz

  cd $STOW

  ./configure \
    --without-docs \
    --without-debug \
    --disable-dependency-tracking \
    --with-extra-charsets=complex \
    --enable-assembler \
    --enable-thread-safe-client \
    --with-big-tables \
    --with-plugin-aria \
    --with-aria-tmp-tables \
    --without-plugin-innodb_plugin \
    --with-mysqld-ldflags=-static \
    --with-client-ldflags=-static \
    --with-plugins=max-no-ndb \
    --with-embedded-server \
    --with-libevent \
    --prefix=$PREFIX

  make install

  cp $PREFIX/share/mysql/mysql.server $PREFIX/bin
fi

INFO="
Set up databases with:

  unset TMPDIR
  mysql_install_db

You can start/stop MySQL with:

  mysql.server start
  mysql.server stop
"
