#!/usr/bin/env bash

PACKAGE=redis

require_version
set_variables

if _install; then
  cd $SRC_PATH
  curl -O http://redis.googlecode.com/files/$STOW.tar.gz
  tar xzf $STOW.tar.gz
  cd $STOW
  make PREFIX=$PREFIX install
fi
