#!/usr/bin/env bash

install_master()
{
  echo "Downloading Dripper"
  _url=https://github.com/fesplugas/dripper/tarball/master

  cd $(mktemp -d /tmp/dripper.XXXXXXXXXX)
  curl -L ${_url} -o dripper.tar.gz
  tar xzf dripper.tar.gz
  cd fesplugas-dripper*
  source script/install
}

install_master
