#!/usr/bin/env bash

set -e

if [ -z $(which stow) ]; then
  echo "\`stow' not installed."
  exit 1
fi

if [ -z $(which bats) ]; then
  echo "bats not installed."
  echo "More info about cram at https://github.com/sstephenson/bats"
  exit 1
fi

./test/*.sh
