#!/usr/bin/env bash

# Usage:
#
#     drip unlink --all
#     drip unlink <package>

source drip-base

set_options $*

if [ -n "$all" ]; then
  stow_unlink_all
else
  source drip-validator
  source $STOW_VERSIONS_PATH/$1
  stow_unlink_one
fi
