#!/usr/bin/env bash

require_darwin() {
  if [ ! $(uname) == 'Darwin' ]; then
    echo "This \`definition' is only valid for Darwin."
    exit 1
  fi
}

require_hg() {
  if [ ! $(which hg) ]; then
    echo "Dripper needs \`hg' installed on the system."
    exit 1
  fi
}

require_bzr() {
  if [ ! $(which bzr) ]; then
    echo "Dripper needs \`bzr' installed on the system."
    exit 1
  fi
}

# TODO: `drip install git` should detect latest version.
require_git() {
  if [ ! $(which git) ]; then
    echo "Dripper needs \`git' installed on the system."
    echo ""
    echo "    drip install git-1.7.10"
    echo ""
    exit 1
  fi
}

require_version() {
  if [ -z "${VERSION}" ]; then
    echo "No version provided."
    exit 1
  fi
}

require_stow() {
  local STOW_VERSION='1.3.3'
  local PACKAGE="stow-${STOW_VERSION}"
  local STOW_BIN_PATH="${STOW_PATH}/${PACKAGE}/bin"

  if [ ! $1 = $PACKAGE ]; then
    if [ -d $STOW_BIN_PATH ]; then
      PATH=$STOW_BIN_PATH:$PATH
    else
      drip install $PACKAGE >> ~/.dripper/install.log
    fi
  fi
}

require_stow $1
