#!/usr/bin/env bash

set -e
[ -n "$DEBUG" ] && set -x

resolve_link() {
  $(type -p greadlink readlink | head -1) "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

find_env_file() {
  local root="$PWD"

  while [ -n "$root" ]; do
    _DRIP_ENV_FILE="${root}/.env"
    if [ -e $_DRIP_ENV_FILE ]; then
      echo "Sourced $_DRIP_ENV_FILE"
      source $_DRIP_ENV_FILE
      break
    fi
    root="${root%/*}"
  done
}

libexec_path="$(abs_dirname "$0")"
export _DRIP_ROOT="$(abs_dirname "$libexec_path")"
export PATH="${libexec_path}:$PATH"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  exec drip-help
  ;;
* )
  command_path="$(command -v "drip-$command" || true)"

  if [ -z "$command_path" ]; then
    find_env_file $1
    exec "$@"
  fi

  if [ ! -x "$command_path" ]; then
    echo "drip: no such command \`$command'" >&2
    exit 1
  fi

  shift
  exec "$command_path" "$@"
  ;;
esac
