#!/usr/bin/env bash
# Usage: drip install <definition>
# Summary: Install a definition

_INSTALL=true

source drip-base
source drip-validator

if [ ! -d $STOW_PATH/$1 ]; then
  source $STOW_VERSIONS_PATH/$1
fi
