#!/usr/bin/env bash

source drip-base

PACKAGES=$(ls -xt ${STOW_PATH})

list_stows() {
  for item in $PACKAGES; do
    current_item=${item##*/}

    if [ $current_item != 'stow-1.3.3' ]; then
      if [ -f ${STOW_PATH}/.stow_${current_item} ]; then
        echo "${current_item} (Linked)"
      else
        echo "${current_item}"
      fi
    fi
  done
}

if [ -n "${PACKAGES}" ]; then
  list_stows
else
  echo "No packages found."
  exit 1
fi
