#!/usr/bin/env bash

source drip-base

PACKAGES=$(ls -x ${STOW_PATH})

list_stows() {
  for item in $PACKAGES; do
    current_item=${item##*/}

    if [ $current_item != 'stow-1.3.3' ]; then
      MESSAGE="${current_item}"
      [ -f ${STOW_PATH}/.stow_${current_item} ] && MESSAGE="${MESSAGE} (Linked)"
      echo $MESSAGE
    fi
  done
}

if [ -n "${PACKAGES}" ]; then
  list_stows
else
  echo "No packages found."
  exit 1
fi
