#!/usr/bin/env bash
# Usage: drip update <definition>
# Summary: Fetch new versions and definitions and update dripper code

source drip-base

require_git

cd $_DRIP_ROOT

if [ -d .git ]; then
  git checkout master
  git reset --hard
  git pull --rebase origin refs/heads/master:refs/remotes/origin/master
else
  git init
  git config core.autocrlf false
  git remote add origin $DRIPPER_REPOSITORY
  git fetch origin
  git reset --hard origin/master
fi
