#!/usr/bin/env bash
# Usage: drip link <definition>
# Summary: Link package

_LINK=true

source drip-base

set_options $*

if [ -n "$all" ]; then
  stow_link_all
else
  source drip-validator
  source $STOW_VERSIONS_PATH/$1
  stow_link_one
fi
