#!/usr/bin/env bash
# Usage: drip unlink <definition>
# Summary: Unlink package
# Help: Uou can also pass the '--all' option to link all installed packages

source drip-base

set_options $*

if [ -n "$all" ]; then
  stow_unlink_all
else
  source drip-validator
  source $STOW_VERSIONS_PATH/$1
  stow_unlink_one
fi
