#!/usr/bin/env bash
# Usage: drip path <package>
# Summary: Show package path

source drip-base
source drip-validator
source $STOW_VERSIONS_PATH/$1

verify_installed $STOW
echo "PATH=$PREFIX/bin:\$PATH"
