#!/usr/bin/env bash
# Usage: drip uninstall <definition>
# Summary: Fetch new versions and definitions

source drip-base

require_git

cd $DRIPPER_ROOT

if [ -d .git ]; then
  git pull --rebase origin refs/heads/master:refs/remotes/origin/master
  git checkout master
else
  git init
  git config core.autocrlf false
  git remote add origin $DRIPPER_REPOSITORY
  git fetch origin
  git reset --hard origin/master
fi
