#!/usr/bin/env bash
# Usage: drip uninstall <definition>
# Summary: Uninstall a definition (unlink and remove)

_UNINSTALL=true

source drip-base
source drip-validator
source $STOW_VERSIONS_PATH/$1

stow_unlink_one
stow_remove
