#!/usr/bin/env bash

source drip-base

# Verify provided folder exists before doing anything, if it does not
# exist exit.
if [ ! -d $STOW_VERSIONS_PATH ]; then
  echo "Provided STOW_VERSION_PATH does not exist."
  exit 1
fi

FILTER="${STOW_VERSIONS_PATH}"
[ $1 ] && FILTER="${STOW_VERSIONS_PATH}/*$1*"
PACKAGES=$(ls ${FILTER})

list_definitions() {
  for item in $PACKAGES; do
    current_item=${item##*/}
    if [ $current_item != 'stow-1.3.3' ]; then
      MSG=${current_item}

      [ -d ${STOW_PATH}/${current_item} ] && MSG="${MSG} Installed"
      [ -f ${STOW_PATH}/.stow_${current_item} ] && MSG="${MSG} Linked"

      echo $MSG
    fi
  done
}

if [ -n "${PACKAGES}" ]; then
  list_definitions
else
  echo "No definitions found."
  exit 1
fi
