#!/usr/bin/env bash

source drip-base
source drip-validator

# Definition exists and is not installed, so go for it!
source $STOW_VERSIONS_PATH/$1

# Show the info ...
[ -z "${INFO}" ] && INFO="No info provided for \`$STOW'."
echo "${INFO}"
